"""fix name by relationship in post

Revision ID: 646f26031cd5
Revises: 9adc796c5226
Create Date: 2023-07-26 03:13:29.948119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646f26031cd5'
down_revision = '9adc796c5226'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
