"""fix name by relationship in subscription

Revision ID: 9adc796c5226
Revises: d2352d6c320f
Create Date: 2023-07-26 03:10:38.685675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adc796c5226'
down_revision = 'd2352d6c320f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
