"""fix relationships

Revision ID: d2352d6c320f
Revises: c6d4cbf2508d
Create Date: 2023-07-26 02:58:49.690931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2352d6c320f'
down_revision = 'c6d4cbf2508d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
